# ===============================================
# ZEUS-IA - Docker Compose para Desarrollo
# ===============================================

version: '3.8'

services:
  # Base de datos para desarrollo
  db:
    image: postgres:15-alpine
    container_name: zeus-db-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: zeus_dev
      POSTGRES_USER: zeus_dev
      POSTGRES_PASSWORD: zeus_dev_password
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - zeus-network

  # Redis para cache y sesiones
  redis:
    image: redis:7-alpine
    container_name: zeus-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    networks:
      - zeus-network

  # Backend FastAPI
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
      target: development
    container_name: zeus-backend-dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/__pycache__
      - /app/.pytest_cache
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
      - DATABASE_URL=postgresql://zeus_dev:zeus_dev_password@db:5432/zeus_dev
      - REDIS_URL=redis://redis:6379/0
      - PYTHONUNBUFFERED=1
    env_file:
      - .env.development
    depends_on:
      - db
      - redis
    restart: unless-stopped
    networks:
      - zeus-network
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  # Frontend Vue.js
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: zeus-frontend-dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
      - VITE_WS_URL=ws://localhost:8000
      - NODE_ENV=development
    depends_on:
      - backend
    networks:
      - zeus-network
    stdin_open: true
    tty: true

  # Nginx para desarrollo (opcional)
  nginx:
    image: nginx:alpine
    container_name: zeus-nginx-dev
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx-dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    networks:
      - zeus-network
    profiles:
      - nginx

volumes:
  postgres_dev_data:
  redis_dev_data:

networks:
  zeus-network:
    driver: bridge