# Railway Configuration for ZEUS-IA Monorepo
# Este archivo configura el despliegue del backend y frontend en Railway

# ============================================
# BACKEND SERVICE - FastAPI + PostgreSQL
# ============================================
[[services]]
name = "zeus-ia-backend"
source = "backend/"

[services.zeus-ia-backend.build]
builder = "NIXPACKS"
buildCommand = "pip install --upgrade pip && pip install -r requirements.txt"

[services.zeus-ia-backend.deploy]
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# ============================================
# FRONTEND SERVICE - Vite + Vue.js
# ============================================
[[services]]
name = "zeus-ia-frontend"
source = "frontend/"

[services.zeus-ia-frontend.build]
builder = "NIXPACKS"
buildCommand = "npm ci && npm run build"

[services.zeus-ia-frontend.deploy]
startCommand = "npx serve dist -s -p $PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
