[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
watchPaths = ["backend/**", "Dockerfile"]

[deploy]
startCommand = "gunicorn app.main:app -c gunicorn.conf.py"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
