[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
watchPaths = ["backend/**", "Dockerfile"]

[deploy]
startCommand = "bash /app/start.sh"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
