[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
watchPaths = ["backend/**", "Dockerfile"]

[deploy]
startCommand = "/app/start.sh"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
