"""Frases del revisor independiente (vuelta 4) que antes preparaban aprobacion contra una retractacion."""

R4_APPROVED_BEFORE = [
 "crea el cliente Ana Ana ana@x.es No Lo Hagas",
 "crea el cliente Ana López Mejor No ana@x.es",
 "crea el cliente Ana López ana@x.es Mejor No",
 "crea el cliente Ana Mejor No ana@x.es",
 "crea el cliente Ana Espera ana@x.es",
 "crea el cliente Ana Cancela ana@x.es",
 "crea el cliente Ana Luego ana@x.es",
 "crea el cliente Ana ana@x.es Cancela",
 "crea el cliente Ana ana@x.es Nunca",
 "crea el cliente Ana ana@x.es Jajaja No",
 "crea el cliente Ana de No ana@x.es",
 "crea el cliente Ana No Lo Crees ana@x.es",
 "crea el cliente Ana No ana@x.es",
 "crea el cliente Ana ana@x.es No",
 "crea el cliente Ana ana@x.es NO",
 "crea el cliente Ana ana@x.es NO LO HAGAS",
 "crea el cliente Ana ana@x.es 🙅",
 "crea el cliente Ana ana@x.es Mañana",
 "crea el cliente Ana Es Broma ana@x.es",
 "crea el cliente Ana ana@x.es Es Broma",
 "crea el cliente Ana ana@x.es Si",
 "crea el cliente Ana Nunca ana@x.es",
 "crea el cliente Ana Tampoco ana@x.es",
 "crea el cliente Ana Despues ana@x.es",
 "crea el cliente Ana ana@x.es Pas Maintenant",
 "crea el cliente Ana ana@x.es Stop",
 "crea el cliente Ana Stop ana@x.es",
 "crea el cliente Ana Wait ana@x.es",
 "crea el cliente Ana ana@x.es no.envies@x.es",
 "crea el cliente Ana no.crees@x.es ana@x.es",
 "envía la oferta del 10% a todos mis clientes no.envies@x.es",
 "envía la oferta del 10% a todos mis clientes no@x.es",
 "envía la oferta del 10% a todos mis clientes 0",
 "envía la oferta del 10% a todos mis clientes 1 2 3",
 "envía la oferta del 10% a todos mis clientes 0 0 0",
 "envía la oferta del 10% a todos mis clientes 100",
 "envía la oferta del 10% a todos mis clientes 10",
 "envía la oferta del 10% a todos mis clientes 5%",
 "envía la oferta del 10% a todos mis clientes 🙅",
 "envía la oferta del 10% a todos mis clientes 👎",
 "envía la oferta del 10% a todos mis clientes ✋",
 "envía la oferta del 10% a todos mis clientes ❌",
 "envía la oferta del 10% a todos mis clientes 🚫",
 "envía la oferta del 10% a todos mis clientes 🛑",
 "envía la oferta del 10% a todos mis clientes ⛔",
 "envía la oferta del 10% a todos mis clientes ...",
 "envía la oferta del 10% a todos mis clientes ?",
 "envía la oferta del 10% a todos mis clientes !!",
 "envía la oferta del 10% a todos mis clientes -",
 "envía la oferta del 10% a todos mis clientes /",
 "envía la oferta del 10% a todos mis clientes #",
 "envía la oferta del 10% a todos mis clientes *",
 "envía la oferta del 10% a todos mis clientes :(",
 "envía la oferta del 10% a todos mis clientes ya",
 "envía la oferta del 10% a todos mis clientes ya ya",
 "envía la oferta del 10% a todos mis clientes lo",
 "envía la oferta del 10% a todos mis clientes se",
 "envía la oferta del 10% a todos mis clientes es",
 "envía la oferta del 10% a todos mis clientes hay",
 "envía la oferta del 10% a todos mis clientes ahora",
 "envía la oferta del 10% a todos mis clientes bien",
 "envía la oferta del 10% a todos mis clientes pues",
 "envía la oferta del 10% a todos mis clientes vale",
 "envía la oferta del 10% a todos mis clientes ｎｏ",
 "envía la oferta del 10% a todos mis clientes mi email nuevo ana@x.es",
 "envía la oferta del 10% a todos mis clientes +34 600 000 000",
 "crea el cliente Ana ana@x.es Ñ",
 "crea el cliente Ana. No ana@x.es",
 "crea el cliente Ana. Cancela ana@x.es",
 "crea el cliente Ana-No ana@x.es",
 "crea el cliente Ana.No ana@x.es",
 "crea el cliente Ana'No ana@x.es",
 "crea el cliente Ana de la No ana@x.es",
 "crea el cliente Ana y No ana@x.es",
 "crea el cliente Ana del No Crees ana@x.es",
 "crea el cliente llamado Ana No ana@x.es",
 "crea el cliente de nombre Ana No ana@x.es",
 "crea el cliente nuevo Ana No ana@x.es",
 "crea el cliente Ana ana@x.es Y Luego Cancela",
 "crea el cliente Ana Y Luego Cancela ana@x.es",
 "crea el cliente Ana Y No ana@x.es",
 "crea el cliente Ana Y Nada ana@x.es",
 "crea el cliente Ana De Momento No ana@x.es",
 "crea el cliente Ana De Momento ana@x.es",
 "crea el cliente Ana Para Mañana ana@x.es"
]
